/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary': '#006e25',
        'on-primary': '#ffffff',
        'primary-container': '#28a745',
        'on-primary-container': '#00330d',
        'primary-fixed': '#83fc8e',
        'primary-fixed-dim': '#66df75',
        'inverse-primary': '#66df75',
        'secondary': '#0060ac',
        'on-secondary': '#ffffff',
        'secondary-container': '#68abff',
        'on-secondary-container': '#003e73',
        'tertiary': '#8f4e00',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#d47c21',
        'on-tertiary-container': '#442200',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'background': '#f4fafd',
        'on-background': '#161d1f',
        'surface': '#f4fafd',
        'on-surface': '#161d1f',
        'surface-variant': '#dde4e6',
        'on-surface-variant': '#3e4a3c',
        'surface-dim': '#d4dbdd',
        'surface-bright': '#f4fafd',
        'surface-soft': '#F8FAFB',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eef5f7',
        'surface-container': '#e8eff1',
        'surface-container-high': '#e2e9ec',
        'surface-container-highest': '#dde4e6',
        'inverse-surface': '#2b3234',
        'inverse-on-surface': '#ebf2f4',
        'outline': '#6e7b6b',
        'outline-variant': '#bdcab9',
        'surface-tint': '#006e25',
        'mentor-ksyu': '#74B9FF',
        'logic-va': '#A29BFE',
        'action-da': '#28A745',
        'error-bagus': '#FF7675',
        'dialogue-bg': '#FFFFFF',
      },
      fontFamily: {
        'sans': ['Inter', 'sans-serif'],
        'display': ['Plus Jakarta Sans', 'sans-serif'],
        'mono': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'part-title': ['36px', { lineHeight: '44px', fontWeight: '800', letterSpacing: '-0.02em' }],
        'chapter-title': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'lesson-header': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-main': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'dialogue-text': ['15px', { lineHeight: '22px', fontWeight: '500' }],
        'code-block': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-bold': ['13px', { lineHeight: '16px', fontWeight: '700' }],
      },
      spacing: {
        'sidebar-width': '280px',
        'content-max-width': '800px',
        'gutter': '24px',
        'section-gap': '48px',
        'component-gap': '16px',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        'sm': '0.25rem',
        'lg': '1rem',
        'xl': '1.5rem',
      },
    },
  },
  plugins: [],
}
